### ISSUE TITLE
How to add Windows ISOs?

### ISSUE THREAD

**Issue by Ali-Shaikh** [nguyentumine/AIO-Boot#1]
How and where should I add windows ISO files so that I can use the usb to install windows?

**Comment by nguyentumine** [comment]
Hi,
Open the ISO file, copy **sources** folder to root directory of USB.

**Comment by Ali-Shaikh** [comment]
can I add multiple ISO? Say for example Win10 and Server 2012 R2?

**Comment by nguyentumine** [comment]
Check this: http://joshcellsoftwares.com/products/winaiomaker/
Or you can rename the folder **sources** every time you want to install.

**Comment by Ali-Shaikh** [comment]
perfect. Thank you
