### ISSUE TITLE
Error when changing language

### ISSUE THREAD

**Issue by sirajuddin97** [nguyentumine/AIO-Boot#10]
Whenever I try to change the language from Vietnamese to English, I get this strange error. Never seen it before. What can I do to fix it?

Screenshot:
![capture](https://cloud.githubusercontent.com/assets/8083228/21471277/c10e8a78-caac-11e6-87fd-976c88d5ba53.PNG)

Thanks in advance.

**Comment by nguyentumine** [comment]
Is this the latest version? Thank you!

1. Show hidden files on your drive.
2. Open file ``/AIO/Tools/config.ini``.
3. Edit or add new line ``lang=en``.
4. Save and Exit.

**Comment by sirajuddin97** [comment]
Thanks!
