### ISSUE TITLE
(invalid)

### ISSUE THREAD

**Issue by ghost** [nguyentumine/AIO-Boot#105]
(invalid)

**Comment by AnomSanjaya** [comment]
what happen with these file?

**Comment by eladkarako** [comment]
never-mind I verified the wim files still have the same name  
at least for  
`WinPE10_8_Sergei_Strelec_x86_x64_2022.01.03_English.iso\SSTR\`  

```txt
strelec8Eng.wim
strelec8NEEng.wim
strelec10Eng.wim
strelec10x64Eng.wim
```
