### ISSUE TITLE
Memtest86 (passmark)

### ISSUE THREAD

**Issue by wjp79** [nguyentumine/AIO-Boot#106]
Hi,

I added memtest86 to AIOboot. Memtest86 starts, but the GUI does not show up completly. Only a small part of the gui is shown. It works fine when I add it on my debian grub config. 

I tried everything, just cant seem to get it working on aioboot. 
I think it has to do something with grub2. When I replace the AIOboot grub files with a copy of debian it seems to run fine. But then I run into other problems. 

Anyone can verify this!?

used following config:

`menuentry "MemTest86 x64 (long load time, be patient)" {
loopback loop /path/to/memtest86-usb.img
chainloader (loop,gpt1)/EFI/BOOT/BOOTX64.efi
}

menuentry "MemTest86 x32 (long load time, be patient)" {
loopback loop /path/to/memtest86-usb.img
chainloader (loop,gpt1)/EFI/BOOT/BOOTIA32.efi
}`

**Comment by putinpe** [comment]
Did you find how to solve?

**Comment by wjp79** [comment]
Yes, 

\boot\grubfm\startup_menu.txt
I added:

`if $EFI64 ; then
	set gmenu="(${user})/MEMTEST86/BOOTX64.EFI"
	set gmenu_title="MemTest86 (UEFI64) 9.5 Beta"
	set gmenu_type=""
	make_entry uefi
	

fi

if $EFI32 ; then
	set gmenu="(${user})/MEMTEST86/BOOTIA32.EFI"
	set gmenu_title="MemTest86 (UEFI32) 9.5 Beta"
	set gmenu_type=""
	make_entry uefi

fi`

Now it just runs fine.
