### ISSUE TITLE
I can't boot Windows 7 or Windows 10 through PXE

### ISSUE THREAD

**Issue by sirajuddin97** [nguyentumine/AIO-Boot#11]
Hi,

I have been trying to set up my PXE boot server all day, and yet it doesn't seem to work. I'm using the newest version of AIO-Boot with no custom settings or anything at all. I will try to explain the whole process as detailed as possible with screenshots of my actions below.

First of all I launched AIO-Boot, clicked on the "Integration" tab and selected my Win10 .iso file:
![image](https://cloud.githubusercontent.com/assets/8083228/21472132/5bb7d7e6-cacb-11e6-815b-24ad84d0290f.png)

I went back to the "Main" tab and clicked "Run PXE". Once the Tiny PXE Server program opened, I tried to connect to the server through another laptop of mine. I enabled UEFI boot through BIOS settings, tried to boot from network and got this error screen:
![2](https://cloud.githubusercontent.com/assets/8083228/21472166/a4aea212-cacc-11e6-803a-dfdfd7287ed3.jpg)

I got this error line on Tine PXE Server at the same time:
![image](https://cloud.githubusercontent.com/assets/8083228/21472198/db42e30a-cacd-11e6-94fb-4724e5113912.png)

Here's the full Tiny PXE log:
> 17:56:47 ROOT=D:\AIO\
17:56:47 TFPTd started...
17:56:47 HTTPd started...
17:56:47 DHCPd:67 started...
18:01:04 DHCPd:INFORM received, MAC:00-0F-FE-FB-5E-53, XID:2AFF3EA2
18:01:42 DHCPd:DISCOVER received, MAC:B4-99-BA-5A-45-CE, XID:8F5F0000
18:01:42 DHCPd:OFFER sent, IP:192.168.0.148, XID:8F5F0000
18:01:43 DHCPd:REQUEST received, MAC:B4-99-BA-5A-45-CE, XID:8F5F0000
18:01:43 DHCPd:ACK sent, IP:192.168.0.148, XID:8F5F0000
18:01:43 TFTPd:DoReadFile OpenError:bootx64.efi Cannot open file "D:\AIO\bootx64.efi". The system cannot find the file specified
18:01:43 TFTPd:DoReadFile OpenError:bootx64.efi Cannot open file "D:\AIO\bootx64.efi". The system cannot find the file specified
18:04:36 DHCPd:INFORM received, MAC:00-0F-FE-FB-5E-53, XID:F62852E4
18:08:59 DHCPd:INFORM received, MAC:00-0F-FE-FB-5E-53, XID:2F289176

Can someone please tell me what I'm doing wrong, and help me fix it? I'm desperate!
Thanks a lot in advance.

Regards,
Sira

**Comment by sirajuddin97** [comment]
Additional info:
I'm able to boot through network when I change my BIOS settings from UEFI to Legacy mode. I can enter different menus, such as WinPE, Disk Utilities, Linux ISO Live etc., but I can't find the Windows 10 .iso file I installed earlier. This is what the boot screen looks like:
![4](https://cloud.githubusercontent.com/assets/8083228/21472273/2d852364-cad1-11e6-8b86-4a7dbda997e7.jpg)

**Comment by nguyentumine** [comment]
You need to use WinPE to install Windows via PXE. After you integrate WinPE 10, just boot into and connect to other computers on your LAN to install using `net use` command. [Video here](https://www.youtube.com/watch?v=uCeMns2wfEM).

To run PXE in UEFI mode

1. Open **AIOCreator.exe** -> **Settings** -> **Configure PXE Boot for UEFI mode** and **Set** it to save.
2. Close **Tiny PXE Server** and run it again.

But this tool does not yet support UEFI mode, you need to do it manually as [here](http://labalec.fr/erwan/?p=791). 

Thank you!

**Comment by sirajuddin97** [comment]
So I can't install Windows 7 or Windows 10 directly through the installation .iso file? I need to use WinPE? Because the reason I'm doing this is to replace the Windows installation CD, so I can install Windows directly through the network instead of saving a bunch of installation USBs and CDs. I got the whole concept wrong here or what?

**Comment by nguyentumine** [comment]
Because you need to use the command line, the network drivers that perhaps they are best supported when using WinPE.

1. Just mount the ISO in the server and share that drive with client.
2. Use WinPE on the client to connect to and run `Setup.exe`.

More information please refer to Google. Thanks!

**Comment by sirajuddin97** [comment]
Thanks a lot for your answers!

**Comment by nguyentumine** [comment]
I have updated the new version and make a video here: https://www.youtube.com/watch?v=K1mDjiIOT9o
Thank you!

**Comment by sirajuddin97** [comment]
You're a saint! Thank you so much.
