### ISSUE TITLE
Menu language reverts back to Vietnamese

### ISSUE THREAD

**Issue by icanhazpython** [nguyentumine/AIO-Boot#12]
Steps to reproduce:

1. Set menu language to english
2. Close tool
3. Reopen tool
4. Add a new boot option (integration)
5. Boot the usb, observe that the menu language has changed back to Vietnamese

**Comment by nguyentumine** [comment]
Confirmed. This will be fixed in the next version.
Thank you!

**Comment by nguyentumine** [comment]
The new version is available, please help me confirm that this bug has been fixed. Thank you!

[AIO Boot v0.9.3.0](https://github.com/nguyentumine/AIO-Boot/releases/tag/v0.9.3.0)

**Comment by icanhazpython** [comment]
Thanks for your responsiveness! I will check it out.


Thank You,
Brett Wilson

**Comment by ZoZat** [comment]
Nope.  Still no English viewable.  I can select any language from the drop down menu. but nothing changes.  I hope this gets resolved soon, it looks like an interesting program.  I'm using the current release.

**Comment by nguyentumine** [comment]
@ZoZat It worked for me.
