### ISSUE TITLE
Support Large FAT32 Volumes

### ISSUE THREAD

**Issue by icanhazpython** [nguyentumine/AIO-Boot#13]
First I wanted to thank you for this tool. It's the first multiboot tool I've used that actually works for every ISO I've added. I wanted to put in a request for support of larger FAT32 volumes. 

A large FAT32 volume can be formatted with this tool on windows: http://www.ridgecrop.demon.co.uk/index.htm?fat32format.htm (the gui tool: http://www.ridgecrop.demon.co.uk/guiformat.exe)

After using this tool, I was able to simply copy over the folders from a smaller AIO boot USB I had. The larger USB was still able to boot & work. So it seems that the AIO Boot extractor tool does not want to extract to the already-formatted larger FAT32 volume (64GB in my case). But the actual setup still works.

**Comment by nguyentumine** [comment]
Thank you!

Well, I use the Windows format tool to perform this task. It is limited to 32GB.

You can format the USB by using other tools, then just select the drive in the list and click the **OK** button to extract and install. Do not select **Auto Format?** option.

I called 7-Zip to extract, I will check this case, but it will not depend on the size of the USB drive, even your hard drive.

**Comment by nguyentumine** [comment]
In the next version, **Auto Format** options will support drives larger than **32GB**.

Thank you very much!

**Comment by nguyentumine** [comment]
The new version is available, please help me confirm that this bug has been fixed. Thank you!

[AIO Boot v0.9.3.0](https://github.com/nguyentumine/AIO-Boot/releases/tag/v0.9.3.0)
