### ISSUE TITLE
No windows iso on AIO menu

### ISSUE THREAD

**Issue by UltimateRandom** [nguyentumine/AIO-Boot#14]
Hey i have one problem, i have used "Integration" and loaded a W7 ISO, now when i boot to AIO there is just no menu to boot this ISO, it is supposed to be called "W7" but it doesn't appear anywhere in the menus.
Also i have a bugs with windows when i use AIO, for example windows shows a blue screen, i have to restart again and works good, not a big issue but i thought it was worth mentioning.

**Comment by nguyentumine** [comment]
It will appear in **WinPE & Setup** menu.
Please send me a screenshot on the second issue. Thank you.

**Comment by UltimateRandom** [comment]
I just have this:
http://imgur.com/b3JRbVL

**Comment by nguyentumine** [comment]
Is it 32-bit or 64-bit?
If it is 32-bit, you need to set it in **Settings** so that the menu appears in UEFI mode.

Have you tried booting USB in Legacy mode?

**Comment by UltimateRandom** [comment]
Yes is 32bits, in legacy mode is working. This is the error that appears sometimes:
http://imgur.com/ylFwr8d
This time i went to Settings and ticked UEFI 32 bits, then load in legacy mode, load the iso but the screen got stuck so i restarted the PC and this error appear. Now i unticked UEFI 32bits and just load in legacy mode, that makes the iso work without problems.

**Comment by nguyentumine** [comment]
Windows 7 32-bit does not support UEFI. It requires Windows 8 or later.
On blue screen of death. This application does not interfere with the system, so I think it is not the cause.
