### ISSUE TITLE
How to defragment that .img file ?

### ISSUE THREAD

**Issue by flyskywhy** [nguyentumine/AIO-Boot#15]
@nguyentumine , in [CLOVER BOOT DISK – CREATE MACOS SIERRA BOOTABLE USB FROM WINDOWS](https://www.aioboot.com/en/clover-boot-disk/) , you said to defragment the .img and .hfs file to avoid unspecified error when selecting them, then which tool can be used to defragment them?

**Comment by nguyentumine** [comment]
You can use [Piriform Defraggler](https://www.piriform.com/defraggler/builds
) to defragment the file that this tool requires. Note that you only need to defragment the file if it causes an error.

![screenshot_1](https://user-images.githubusercontent.com/13947826/28368784-d14186b0-6cbf-11e7-981c-380df8701182.jpg)

**Comment by flyskywhy** [comment]
I let Defraggler defrag the Clover.img, but still the same error. I change OS from Win7 to WinPE, still error. I change another USB disk, still error.
![image](https://user-images.githubusercontent.com/1439846/28464259-f3480886-6e56-11e7-99dc-1ee4dcb74dfb.png)

**Comment by nguyentumine** [comment]
What format is your drive in? FAT32 or NTFS?

**Comment by flyskywhy** [comment]
One USB disk is NTFS, another one is FAT32, all error.
Then I `CONVERT volume /FS:NTFS` that FAT32 to NTFS, still error; then I directly format it to NTFS, still error.
ps, my windows language is Simplified Chinese.

**Comment by nguyentumine** [comment]
Another user has encountered the same problem. You need to use [diskpart](https://technet.microsoft.com/en-us/library/cc766465(v=ws.10).aspx) to repartition the USB.

```
list disk
select disk [disk number]
clean
create part pri
format fs=ntfs quick
assign
```

Thank you!

**Comment by flyskywhy** [comment]
Yes, that works.
Thank for your great software!

**Comment by MrVodinn** [comment]
Unfortunately, I have trued both ways, but still have the issue.

![image](https://user-images.githubusercontent.com/6102635/48581083-e3d73000-e931-11e8-8b32-460840b9f198.png)
