### ISSUE TITLE
Grub2 shim

### ISSUE THREAD

**Issue by Sporesirius** [nguyentumine/AIO-Boot#16]
Hello,
I tried to install grub2 with shim but some modules are blocked by secure boot.

error: Secure Boot forbids loading module from (hd0, msdos1) /boot/grub/x86_64-efi/usb.mod

Does anyone know how to fix this?

I use Ubuntu to install grub2 and shim on a USB stick

**Comment by nguyentumine** [comment]
Read this: https://www.aioboot.com/en/secure-boot/

**Comment by Sporesirius** [comment]
Thanks
