### ISSUE TITLE
Windows Setup imdisk

### ISSUE THREAD

**Issue by Sporesirius** [nguyentumine/AIO-Boot#18]
Hello, it's me again,
I just wanted to ask, how can I run the Programm ImDIsk from the Windows Setup to open a Windows ISO?

I looked at it, but it did not work: https://www.aioboot.com/en/install-windows/

**Comment by nguyentumine** [comment]
From inside Windows Setup, press Shift+F10 to open a command prompt window. 
Install ImDisk and then mount the ISO file.

Sorry but I will not answer the questions that seem unrelated to AIO Boot here.

**Comment by Sporesirius** [comment]
But is it not realized in AIO Boot with ImDisk?
Thought this principle is in AIO boat?

**Comment by nguyentumine** [comment]
Yes.
https://www.aioboot.com/en/windows-installation/
