### ISSUE TITLE
Can't deploy an ReactOS LiveCD last build.

### ISSUE THREAD

**Issue by DartPower** [nguyentumine/AIO-Boot#19]
![image](https://user-images.githubusercontent.com/2005369/39676091-0b535bca-516d-11e8-939e-c71b1ee5a32c.png)

Downloaded from here:
https://reactos.org/getbuilds/

**Comment by nguyentumine** [comment]
`reactos-livecd-0.4.9-dev-843-g3bf2f30-x86-gcc-lin-dbg.iso`

I have downloaded the latest version and it is supported.
The `msvc-win` version is not supported, it seems that its `/loader/setupldr.sys` file is invalid. Open up ISO and copy `/loader/setupldr.sys` from the `gcc-lin` version, then save the ISO file and integrate it.

**Comment by DartPower** [comment]
Thanks a lot!
