### ISSUE TITLE
WinPE and DaRT integration from ISO doesn't work

### ISSUE THREAD

**Issue by aleaksunder** [nguyentumine/AIO-Boot#22]
It stops after menu item name request...

![image](https://user-images.githubusercontent.com/40979373/42434531-0d7a3d7e-8386-11e8-8648-7c292dd63581.png)

Checked with v0.9.8.12 through the v0.9.8.2... It works with v0.9.8.2 and doesn't with v0.9.8.3 and later

I've tried it all with the latest Windows 10 x64 host

**Comment by nguyentumine** [comment]
Send me the file **/AIO/Tools/error.log**, I will check it.

**Comment by aleaksunder** [comment]
[error.log](https://github.com/nguyentumine/AIO-Boot/files/2175291/error.log)

Here it is... After fresh deployment of v0.9.8.12 and one attempt to integrate ISO there is only one string:
09.07.2018 16:30:10 - 1372 - Windows 10 (Version 10.0, Build 17134, 64-bit Edition)

**Comment by nguyentumine** [comment]
Open the ISO file, select the **\sources\boot.wim** file to integrate. Currently I have not found the cause.

**Comment by nguyentumine** [comment]
```
ImDisk.exe -a -m Z: -f /path/to/winpe.iso
echo %errorlevel%
```

Because ImDisk returns code that failed to mount your ISO file.
Please try it manually and check the return code.

**Comment by aleaksunder** [comment]
Oh, you are right... It seems that one of third party software has installed an older version of ImDisk driver, after manually removing it all integrations are working now

Big thanks!

**Comment by aleaksunder** [comment]
It is strange, but all other integrations from ISO, such as Ubuntu etc worked well before...
You may close this issue if only PE and DaRT integrations functioning through ImDisk

**Comment by nguyentumine** [comment]
Because I use 7-Zip to extract non-Windows ISO files.
