### ISSUE TITLE
Add the Indonesian Language

### ISSUE THREAD

**Issue by AnomSanjaya** [nguyentumine/AIO-Boot#25]
Hello...

I’am are AIOBOOT user in Indonesia, your tool is very awesome & useful, im use it in my HDD external.

But this program not including Indonesian Language since firstly version released, so i create a translation for next version of AIOBOOT, for helping other Indonesian users to more easily using this tool while maybe they not understand with English language. Maybe some word in translation was misleading, but it will be fixing as i can later.

I Hope u to like it.

Thank You.

[id.txt](https://github.com/nguyentumine/AIO-Boot/files/2434576/id.txt)

**Comment by nguyentumine** [comment]
Hi,

I checked your translation, I found many lines that you did not translate properly, one of which is the content in the About tab. I hope you will correct the translation, then I will add it to the next version.

**Comment by AnomSanjaya** [comment]
Hello, 

Thank you for this evaluation, im uploading revision of this translate. Many translate word was fixed. But, the text are like boot, bootloader, LiveCD, Setup, multiboot etc. there is no translation at all in indonesian. I tried to simplify the language so that it was easy to understand.

Thank You. 

[id.txt](https://github.com/nguyentumine/AIO-Boot/files/2441042/id.txt) Revision

**Comment by nguyentumine** [comment]
I will check it soon, thank you.

**Comment by AnomSanjaya** [comment]
New update of AIO Boot translation to Indonesian Language

*re-translate from zero based AIO-Boot latest version

[id.txt](https://github.com/nguyentumine/AIO-Boot/files/5146458/id.txt)

**Comment by nguyentumine** [comment]
Thanks for your help. Your language file is included in the new version.
