### ISSUE TITLE
Duplicated files in install.iso with "Extract WIM for Windows Setup"

### ISSUE THREAD

**Issue by FarukGamer** [nguyentumine/AIO-Boot#27]
I dont know if this is a bug. but this seems to make the install.iso 3 times larger then normal.

![winrar_2018-10-03_18-10-33](https://user-images.githubusercontent.com/12494967/46423869-e42bbb00-c737-11e8-9cef-b3fc17ef3e2a.png)

**Comment by nguyentumine** [comment]
I use mkisofs to repack the ISO file. Do you use the original ISO version of Microsoft or a modified version?

**Comment by FarukGamer** [comment]
I am using Both and their have the same result.

**Comment by CattoGamer** [comment]
Issue still persistent and not resolved after 3 years, Closed.
