### ISSUE TITLE
Website https error

### ISSUE THREAD

**Issue by iqqmuT** [nguyentumine/AIO-Boot#28]
This is not really an issue with the repo, but I didn't know where else to put this.

www.aioboot.com uses an invalid security certificate.

The certificate expired on October 19, 2018, 4:34:47 AM GMT+3. The current time is October 19, 2018, 1:21 PM.

Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by nguyentumine** [comment]
Thank you, I don't have much time to visit this site. I have renewed the certificates.
THanks!
