### ISSUE TITLE
Adding Win8.1 ISO does not create UEFI BCD

### ISSUE THREAD

**Issue by steve6375** [nguyentumine/AIO-Boot#3]
If adding a Win8.1 ISO, only the MBR mode is created, not the \EFI BCD.
I used Win10 x64 MBR OS to run AIO Boot

**Comment by nguyentumine** [comment]
Yes, since most computers will only work with UEFI mode on 64-bit architecture
32-bit architecture is not supported because it is not common

**Comment by steve6375** [comment]
It was a 64-bit ISO and I was running AIOCreator.exe on a 64-bit Win10 system.

**Comment by nguyentumine** [comment]
Thank you, what build version of this ISO you are using?

**Comment by steve6375** [comment]
I tried adding same ISO again Win8.1 x64 Retail English, on fresh USb drive. This time I got a UEFI BCD and it does UEFI-boot now. Not sure why it did not work before...
