### ISSUE TITLE
Tiny PXE Server: Access Denied

### ISSUE THREAD

**Issue by marrobHD** [nguyentumine/AIO-Boot#30]
Tiny PXE Server wont start:

21:07:31 ROOT=D:\AIO\
21:07:31 DHCPd 192.168.178.39:67 started...
21:07:31 DHCPd 192.168.178.39:4011 started...
21:07:31 TFPTd 192.168.178.39:69 started...
21:07:31 httpd error, Socket Error # 10013
Access denied.

Thanks for help

**Comment by ddybing** [comment]
Hi!

Checklist:
1. Do you have another web server running on the computer which has bonded itself to port 80?
2. Do you have a firewall or antivirus software running that may be blocking the port?
3. Did you reboot while Tiny PXE Server was running without first turning it off?
