### ISSUE TITLE
Possible to use port 81 instead of 80

### ISSUE THREAD

**Issue by mcharman77** [nguyentumine/AIO-Boot#43]
Hi there, great project. Just wondering if its possible to use port 81 (or another port) instead of port 80 for the http server running on tiny pxe server. I have something else already running on port 80. Apologies if this is a basic thing... I’m somewhat new to this.

**Comment by ddybing** [comment]
Yes, this is possible. 

Please add 
`[web]
port=81
`

to the end of your Tiny PXE Server config file. The file is _config.ini_ and can be found at \AIO\Tools\PXE

:-)

**Comment by mcharman77** [comment]
Thanks for your reply.
I did try this but unfortunately it didn't work. Although Tiny PXE server can be configured to work on port 81 (or another port), the software that in executed on the PC that I want to network boot seems to be hard coded to get the menu from port 80. Changing the Tiny PXE Server config file have no affect on that.
Any other thoughts?
Thanks again!

    On Sunday, 15 March 2020, 17:39:59 GMT-4, Daniel Dybing <notifications@github.com> wrote:  
Yes, this is possible.

Please add
`[web]

port=81
`

to the end of your Tiny PXE Server config file. The file is config.ini and can be found at \AIO\Tools\PXE

:-)

**Comment by ddybing** [comment]
Hi!

You seem to be correct. Once you click "Run PXE" the config file is overwritten and the standard port (80) is used. You _could_ just run the Tiny PXE Server executable directly instead of going through AIOBoot, that would keep your config file intact (this works, I just tested it). 

But as for launching Tiny PXE Server through AIOBoot I think you're out of luck, at least if you're looking for a quick and easy solution.

**Comment by mcharman77** [comment]
Hi,

I actually did try running as you did - running the Tiny PXE Server directly, and I see it runs on the port I specify in the config.ini file The problem now is on the remote PC side I want to boot from the network... it connects to the Tiny PXE server and then it always looks for something running on port 80...

**Comment by ddybing** [comment]
The boot-url variable (seen as ${boot-url} in the menu file) seems to be hardcoded into the kernel, but you can override it in the menu file. 
On the line after #!ipxe in the menu file, just add 

`set boot-url http://IP:81`

Replace IP with the IP of the computer Tiny PXE server is running on, and 81 with the port you are listening on. 

I have confirmed this to be working just now.

**Comment by mcharman77** [comment]
Works great! Thank you!
And actually what I’ve been trying to do is use the AIO gui to configure the menu etc., and then use my ASUS router as the PXE server. I just need to clean a few things up now and think it should be working shortly.
Thanks again.
