### ISSUE TITLE
How can I boot from a USB drive but remotely access the HTTP data? Basically change the HTTP IP address it connects to

### ISSUE THREAD

**Issue by asheroto** [nguyentumine/AIO-Boot#44]
I'd like to be able to boot from a flash drive with the boot files & data files hosted remotely.

I know the data is accessed over HTTP, basically I'd just like to be able to choose a different IP for the data.

**Comment by ddybing** [comment]
This is an old issue, but I'll answer. 

This is possible, but not directly through the interface of either AIOBOOT or Tiny PXE Server. 

What you have to do is edit the menu.ipxe file located at \AIO\Tools\PXE. This is the menu file that is loaded by the iPXE kernel that the client first loads. iPXE already uses HTTP/HTTPS for almost everything, so you just have to edit the location of the needed files (e.g. boot.wim) to point to your desired IP and location (e.g. http://yoursite.com/files/boot.wim). 
For more information, take a look at https://ipxe.org/ which has is the official site of iPXE, and that has a lot of documentation.

**Comment by asheroto** [comment]
@ddybing got it.  Thanks so much for replying.
