### ISSUE TITLE
Adding clonezilla-live-2.4.7-8-amd64.iso gives error in AIO

### ISSUE THREAD

**Issue by steve6375** [nguyentumine/AIO-Boot#5]

**Comment by nguyentumine** [comment]
Work for me...

**Comment by steve6375** [comment]
My drive is an 8GB FAT32 USB drive with over 4GB of free space. I created it with BootIce using  2048 and 32 reserved as suggested (MBR partition). My Windows is 64-bit Win 10 1607.

**Comment by steve6375** [comment]
pmagic_2016_01_06..iso also doesn't install (Error! at end of copy operation).
Could there be something it doesnt like about my USB drive?

**Comment by steve6375** [comment]
Same with gparted-live-0.8.1-3.iso - says 'cleaning up' and then get Error!

**Comment by nguyentumine** [comment]
I've added Gparted without problem, do you want to try new version of AIO Boot?

**Comment by steve6375** [comment]
I just used bootice again and made fresh USb drive. clicked on grub2 and then tried gparted iso - same issue - at end after 'cleaning up' I get Error!

**Comment by steve6375** [comment]
Where is new version?

**Comment by nguyentumine** [comment]
This is pre-release, thank for interesting
[AIOBoot-v0.9.0.1b4.7z](https://drive.google.com/file/d/0B-o-S1Ld1ZTidHJMcm1mT0xRSjA/view?usp=sharing)

**Comment by nguyentumine** [comment]
In new version, you can use ISO file larger than 4GB on FAT32 partition for Windows Setup. You can also use the ISO file created from [Media Creation Tool](https://www.microsoft.com/en-au/software-download/windows10)

**Comment by steve6375** [comment]
I tested with gparted ISO. It did copy files and make the menu OK. But it failed to boot (squashfs error).
I will test more tomorrow. Thanks.

**Comment by nguyentumine** [comment]
Hi, please help me try this version, use option **Linux OS** > **Auto Detect** to add Gparted, CloneZilla and Parted Magic

[AIOBoot-v0.9.0.1b5.7z](https://drive.google.com/file/d/0B-o-S1Ld1ZTiLW1wZ2E1TC15RkU/view?usp=sharing)

Thank you!

**Comment by nguyentumine** [comment]
[AIOBoot-v0.9.0.1b6.7z](https://drive.google.com/file/d/0B-o-S1Ld1ZTicEpwNHVrQlgxMWM/view?usp=sharing)

**Comment by nguyentumine** [comment]
[AIOBoot-v0.9.0.1b9.exe](https://drive.google.com/file/d/0B-o-S1Ld1ZTieGFLM1RGYTBHdUk/view?usp=sharing)
