### ISSUE TITLE
Why the latest AIO-Boot not supported HDD External?

### ISSUE THREAD

**Issue by AnomSanjaya** [nguyentumine/AIO-Boot#55]
Hello, i want to ask u "why the latest AIO-Boot no longer supported HDD External again?"

*i have only 500 GB HDD External
*i use this tool for booting WinPE (such as Strelec & Macrium Reflect for data recovery and ghosting purpose)
*i dont know why the all Windows wasn't installed over HDD External (only work on USB)

**Comment by ddybing** [comment]
I believe this was removed as the developer found that many were wiping their other drives unintentionally. 
IIRC he is working on a improved version for this feature. 

In the meantime you can extract the AIOBoot zip archive to your external drive, then run AIOCreator and choose to install the Grub2 bootloader on your external drive.

**Comment by nguyentumine** [comment]
I have temporarily dropped support for HDD because many users have installed AIO Boot on their C drive. But they don't know how to uninstall, deleting files on the drive will result in Grub2 no longer working properly.
I added back to support the hard drives but limited to disk 0.

**Comment by nguyentumine** [comment]
> *i dont know why the all Windows wasn't installed over HDD External (only work on USB)

Is your external disk GPT or MBR, it boot in UEFI or MBR?

**Comment by AnomSanjaya** [comment]
My external disk GPT style, only boot at UEFI
