### ISSUE TITLE
Suggestion: replace bootx64.efi with shimx64.efi

### ISSUE THREAD

**Issue by steve6375** [nguyentumine/AIO-Boot#6]
Why dont use rename shimx64.efi as bootx64.efi?
Then it will secure boot or non-secure boot with no need to type any commands in UEFI shell?

**Comment by nguyentumine** [comment]
Thanks, but my computer does not have Secure Boot feature, so I'm not sure it will work, is it work for you?

**Comment by steve6375** [comment]
yes, works fine.

**Comment by nguyentumine** [comment]
Wow, thank you so much
I will replace bootx64.efi as you suggested with auto detect ISO of Linux OS  :)

**Comment by nguyentumine** [comment]
Hey, are you the author of Easy2Boot? I learned a lot from you...

**Comment by steve6375** [comment]
yes.
