### ISSUE TITLE
what's the default account when write kali linux image into USB Driver in persistent mode?

### ISSUE THREAD

**Issue by tlsalex** [nguyentumine/AIO-Boot#62]
1. I use AIO-Boot to write kali linux image into my usb.
2. I boot computer from my usb.
3. From the grub2. I choose [2] Linux OS ,then choose my kali linux.
4. original kali image itself has a boot menu , which I can choose live mode or install kali.
5. But from AIO-Boot, after choose kali linux , I can not choose to run kali in live mode or make an installation.

PS : kali linux version is 2020.3

Any advice ?

**Comment by tlsalex** [comment]
I think kali linux was write to my usb in persistent mode.
But what is the default account when it boot into the login interface.
I got stuck at login interface.

**Comment by tlsalex** [comment]
Or how to force AIO use the default mode (none persistent mode)  to write my image to USB Drive.

**Comment by nguyentumine** [comment]
Copy ISO file to AIO Boot drive. From the Grub2 menu, select **ISO & IMG Mapper**, then choose your ISO file to boot

**Comment by nguyentumine** [comment]
@tlsalex I have tested with the latest version. It seems to only support FAT32, not NTFS. 
Run AIOCreator.exe, from the drop-down list, choose Auto Detect instead of Kali Linux.
It supports persistent mode.

**Comment by tlsalex** [comment]
@nguyentumine  thanks, but I don't want AIO to write kali linux in persistent mode , as it do not allow me boot kali linux in live mode.

If it write kali linux in persistent mode, the default account did not work at all.

**Comment by nguyentumine** [comment]
It works perfectly for me!
Persistent mode, the tool will popup a dialog to ask you, just answer No.
Furthermore, you can boot ISO file directly from Grub2 without having to use AIOCreator.
![2020-08-21_105220](https://user-images.githubusercontent.com/13947826/90850646-77a61d80-e39c-11ea-8c7c-453c1ad1fbac.png)

New version available, try if that doesn't work.

**Comment by tlsalex** [comment]
@nguyentumine  which version of kali linux you use when you test it, it's 2020.3 ? I use kali 2020.3 , it does not work from "Boot from ISO, WIN & VHD",  from this webpage "https://www.aioboot.com/en/boot-linux-iso/" , seems it has a script to detect ISO file.
`For Linux ISO files, the script will automatically detect which distributions it supports. `
Maybe kali 2020.3 is too new , the script can not detect it. then fail to boot it.

![image](https://user-images.githubusercontent.com/36788337/90852871-43862900-e3ab-11ea-82f0-c4c01920103c.png)

but from "ISO & IMG Mapper" , it does work well.

**Comment by nguyentumine** [comment]
@tlsalex I use version 2020.3 too. Have you updated to the latest version?

**Comment by tlsalex** [comment]
@nguyentumine , before, I used  AIO Boot v0.9.9.5, and now, I update to AIO Boot v0.9.9.6,
 but I still fail to boot kali 2020.3 from "Boot from ISO, WIM & VHD" .
Just like above screen shot, at step 3, I don't how to make it start to run from the menu.

Again. "ISO & IMG Mapper' work well to run kali 2020.3.

Thank you.

**Comment by tlsalex** [comment]
@nguyentumine , AIO it does work and work well , it was because I did not choose the right device from menu .
Thank you
