### ISSUE TITLE
Fedora-Workstation-Live fails to boot in MBR BIOS mode

### ISSUE THREAD

**Issue by wimbrts** [nguyentumine/AIO-Boot#63]
Thanks for new version 0.9.9.8 which has UEFI Secure boot support working well.

Fedora-Workstation-Live-x86_64-32-1.6.cfg contains lines wit **linuxefi** and **initrdefi** suitable for booting in UEFI Secure mode,
but [Fedora-Workstation-Live](https://getfedora.org/nl/workstation/download/) fails to boot in MBR Legacy BIOS mode booting with Grub2 (Grub4dos Menu entry is working OK).

I solved the issue by using **linux** and **initrd** as commands which are valid for both booting modes.

**Comment by nguyentumine** [comment]
Thank you very much. I use these functions as aliases for the linux and initrd commands for 2018 and earlier versions.

It seems that the script does not accept placing the function command inside the if condition so we need to create a new file.

**AliasCmds.cfg**:
```
function linuxefi {
	linux $@
}
function initrdefi {
	initrd $@
}
```
**Functions.cfg**:
```
if [ "${grub_platform}" == "pc" ]; then
	source ${prefix}/AliasCmds.cfg
fi
```

**Comment by wimbrts** [comment]
OK, good to hear that you know what is causing the issue. 👌😀

**Comment by nguyentumine** [comment]
Thank you.  New version is available and this issue has been fixed.

**Comment by wimbrts** [comment]
Thank you and I will do some testing 😀

**Comment by wimbrts** [comment]
Fedora booting OK now in MBR Legacy BIOS and in UEFI Secure mode 😀
