### ISSUE TITLE
Cannot install grub2 on fat32 usb drive (PBR at LBA63)

### ISSUE THREAD

**Issue by steve6375** [nguyentumine/AIO-Boot#7]
Rufus uses a boot.img and core.img which just fits into LBA0-LBA62 and so grub2 can be installed on disks which have a PBR at LBA63 (many do).
I suggest using his grub2 files and then you will not have the problem of having to reformat your existing disk using BootIce.
http://pete.akeo.ie/2014/05/compiling-and-installing-grub2-for.html
http://rufus.akeo.ie/

It supports MBR partitions for FAT, exFAT and NTFS.
[RufusGrub2.zip](https://github.com/nguyentumine/AIO-Boot/files/478154/RufusGrub2.zip)

**Comment by nguyentumine** [comment]
Hi, thank you
I think Rufus will not work on any disk that has multiple partitions, ie Grub2 not be placed on the second partition and it is not the perfect solution for use in hard disk

**Comment by nguyentumine** [comment]
With AIO Boot, you can place the **EFI folder** on the FAT32 partition for UEFI support, then put the **AIO folder** on NTFS partitions for support files larger than 4GB
Have you tried this yet?

**Comment by steve6375** [comment]
I have not tried it yet. Will it work on a Removable USB drive or only on a USb HDD?
I used the grub2 files from Rufus on AIOBoot and it worked OK (booting to \boot\grub\grub.cfg).

**Comment by nguyentumine** [comment]
Try repartition your USB with multiple partitions or using HDD and try to put Grub2 (AIO or Boot folder) on the second partition...
