### ISSUE TITLE
Windows installation error (Secure boot enable)

### ISSUE THREAD

**Issue by mummy1990** [nguyentumine/AIO-Boot#73]
![thumbnail_20200922_194819](https://user-images.githubusercontent.com/45992850/93934935-8598e680-fd2c-11ea-9cde-b415a5cedd54.jpg)

Hi,
I see last 2 update (v0.9.9.14 (21.09.2020) and v0.9.9.13 (17.09.2020)) has error.
I do install Aio Boot to a hard drive from scratch. I integrate MSDN Windows normally. After 100% it gives the error in the screenshot I shared just before rebooting. 

- I tried install to UEFI and Secure Boot enabled. Installation can't completed.
- Secure boot disabled and uefi enabled, installation is ok.
- Legacy boot windows installation is ok.

Secure boot has problem. How can I fix this problem. I share screenshot on attachment.

I tried last 7 version and results:

- AIO Boot v0.9.9.8 - installation successfully
- AIO Boot v0.9.9.9 - installation successfully
- AIO Boot v0.9.9.10 - installation successfully
- AIO Boot v0.9.9.11 - installation fault
- AIO Boot v0.9.9.12 - installation fault
- AIO Boot v0.9.9.13 - installation fault
- AIO Boot v0.9.9.14 - installation fault

Sorry my bad english. I used google translate. Thank you.

_Note: I dont use ISO boot, I'm use iso integration mode._

**Comment by nguyentumine** [comment]
I have tested and encountered the same problem. Try the option below:

1. Open **/AIO/grub/grub.cfg**.
2. Delete these lines:
```
fucksb -i
fucksb --off
```
3. Save the file then try again.

Thanks!

**Comment by CILGIN06** [comment]
AIO_Boot v0.9.9.14 and
AIO_Boot v0.9.9.15 application
With SecureBoot = Enabled, when attempting to install Windows using the AIO Main Menu "WinPE & Setup", after the "Loading Files ..." screen, the system restarts and windows cannot be installed.

Secure boot disabled and uefi enabled, installation is ok.
Legacy boot windows installation is ok.

Integrated system Windows_10_2004_x64_MSDN
