### ISSUE TITLE
SecureBoot==Enabled "WinPE & Setup" Windows cannot be installed

### ISSUE THREAD

**Issue by CILGIN06** [nguyentumine/AIO-Boot#74]
AIO_Boot v0.9.9.14 and
AIO_Boot v0.9.9.15 application
With SecureBoot = Enabled, when attempting to install Windows using the AIO Main Menu "WinPE & Setup", after the "Loading Files ..." screen, the system restarts and windows cannot be installed.

Secure boot disabled and uefi enabled, installation is ok.
Legacy boot windows installation is ok.

Integrated system Windows_10_2004_x64_MSDN

**Comment by nguyentumine** [comment]
Try this, download and extract this file to get **grubx64.efi** file then copy it to **/EFI/BOOT** directory.
[grubx64.efi.zip](https://github.com/nguyentumine/AIO-Boot/files/5287986/grubx64.efi.zip)

**Comment by CILGIN06** [comment]
Thank you for your attention.

Usage results with the grubx64.efi file in "AIO_Boot_v0.9.9.15"

SecureBoot == Enabled ==> "WinPE & Setup" ==> Win10_2004_x64_MSDN_ (19041.264) ==> Windows installation successful.

SecureBoot == Enabled ==> "WinPE & Setup" ==> Win10_2004_19041.508_x64 ==> Windows setup failed


Usage results with the grubx64.efi file you sent

SecureBoot == Enabled ==> "WinPE & Setup" ==> Win10_2004_x64_MSDN_ (19041.264) ==> Windows installation successful.

SecureBoot == Enabled ==> "WinPE & Setup" ==> Win10_2004_19041.508_x64 ==> Windows setup successful


"[d] Disable Secure Boot for this session" ==> If SecureBoot == Disable 

"WinPE & Setup"			Windows installation successful. (v19041.264 and v19041.508)
“Install Windows from ISO”	Windows installation successful. (v19041.264 and v19041.508)
“File Manager” “G2FM”		Windows installation successful. (v19041.264 and v19041.508)


![2020-09-27_18h25_45](https://user-images.githubusercontent.com/65132092/94369960-754e8600-00f5-11eb-8f09-ef9b78f89ccf.jpg)

![2020-09-27_18h26_07](https://user-images.githubusercontent.com/65132092/94369963-7bdcfd80-00f5-11eb-9908-a479683fca09.jpg)

![2020-09-27_18h53_06](https://user-images.githubusercontent.com/65132092/94369970-91522780-00f5-11eb-9438-1ab0191f226b.jpg)

![2020-09-27_18h27_23](https://user-images.githubusercontent.com/65132092/94369997-b9da2180-00f5-11eb-917c-7a9f697da9db.jpg)

![2020-09-27_18h29_59](https://user-images.githubusercontent.com/65132092/94369979-9ca55300-00f5-11eb-9588-9ea178a99615.jpg)

![2020-09-27_18h40_44](https://user-images.githubusercontent.com/65132092/94369986-ab8c0580-00f5-11eb-9254-7a8cbf42bf71.jpg)

**Comment by koylumail** [comment]
Great. Thank you!

**Comment by CILGIN06** [comment]
AIO_Boot v0.9.9.16 ==> SecureBoot==Enabled ==> "WinPE & Setup"  ==> 20H2_19042.541_x64
Windows installation successful.

![2020-09-28_14h26_30](https://user-images.githubusercontent.com/65132092/94431741-59eb8580-019e-11eb-877f-af057b62bc47.jpg)

![2020-09-28_14h46_31](https://user-images.githubusercontent.com/65132092/94431756-5e17a300-019e-11eb-8a00-ac2d11ee0385.jpg)
