### ISSUE TITLE
Legacy Windows Install Menu Not Work

### ISSUE THREAD

**Issue by Se7Touch** [nguyentumine/AIO-Boot#80]
Hi, I'm integrate windows 10 in multiboot and after plug pendrive to pc.

Grub2 menu is done, but i try to enter win setup menu and I see this error..

![Ekran Resmi 2020-10-09 00 38 13](https://user-images.githubusercontent.com/16725944/95516902-a87ff780-09c8-11eb-824a-cb2d9e7412b0.png)

**Comment by nguyentumine** [comment]
"Install Windows from ISO"
Try this entry from Grub2 main menu.

**Comment by Se7Touch** [comment]
But i use WIM for windows install option. i have not iso.

**Comment by ddybing** [comment]
How have you integrated your WIM file, and what WIM file have you used - boot.wim or install.wim/install.esd?

**Comment by Se7Touch** [comment]
> How have you integrated your WIM file, and what WIM file have you used - boot.wim or install.wim/install.esd?

u can just enable Extract for Windows Setup in AIO Settings and after windows integrations using the wim method.

**Comment by nguyentumine** [comment]
The current bootmgr version does not support the exfat format.
