### ISSUE TITLE
Kali Linux 2020.3 live version is unable to boot

### ISSUE THREAD

**Issue by Xnehaxixh** [nguyentumine/AIO-Boot#84]
The iso can be found here.
https://www.kali.org/downloads/

**Comment by nguyentumine** [comment]
I have tested with this version and it all works. Are you using NTFS or FAT32 format for AIOBOOT drive? If NTFS, try formatting the drive to FAT32.

**Comment by Xnehaxixh** [comment]
I did a proper setup this time. It is working well. Thanks.
