### ISSUE TITLE
Mix with Easy2Boot

### ISSUE THREAD

**Issue by fanchyfanch** [nguyentumine/AIO-Boot#9]
Hi,

It's not really an issue I want to report but more a suggestion I wanted to make and didn't find anywhere else to contact you (sorry, my vietnamese is not so good, I'm french!).

I think you already know Easy2Boot which is based on Grub4Dos since I've seen its designer posting issues on your Github (steve6375).

I used his solution for years now because it was the easier for me to work on Windows based computer, until I discover your work which greatly impressed me.

I'm working with an Zalman V300 which is a USB 3.0 HDD enclosure which emulates ISO files in a virtual CD : 
https://www.amazon.com/Zalman-ZM-VE350-External-Enclosure-ZM-V350B/dp/B019C23H06/ref=sr_1_fkmr1_2?ie=UTF8&qid=1478819491&sr=8-2-fkmr1&keywords=zalman+v300

Easy2Boot is made in a way to be compatible with this hardware (ISO files must be place in a root folder "_ISO").

Also, I've seen you integrate Grub4Dos in your solution.

I tried to mix both your solutions and it's pretty working but that would be a lot better if you could work together so the Grub4Dos solution of Easy2Boot would be the fallback of your excellent Grub2 solution.

For example, your solution creates a /AIO/WS folder for Windows installs and WinPE ; thus, Easy2boot uses the /_ISO/WINDOWS/WINxxx (where "xxx" is the version, i.e. 7/8/10) for installs and /_ISO/WINPE). 

Wouldn't it be nice to have the same folder for payload files while the configuration would work indifferently for Grub Legacy and Grub2 ? (hope I'm clear on it)

This would have great advantages (for BIOSes on old system and the new EFI boot) and would cover a wider range of configurations, I think.

Thanks for reading my suggestion (hoping to you both could come up soon with an only solution in this way).

Once again, "bravo" for this work and thanks for everything.
Fanch

**Comment by nguyentumine** [comment]
I understand what you're saying. I wanted to use the **/AIO/WinSetup** directory instead but XP will not work on FAT32 if the directory has more than 10 characters (I don't remember exactly). Most Linux packages are extracted. So I can not mix them.
Thank you for your suggestion.
